
# Name of the application
name = "hello-py"

[Build]

  # Command to build the application, valid variables: $ROOT, $APPNAME
  command = "python hello.py"

  # Repository relative paths to baur include files that the build inherits.
  # Valid variables: $ROOT
  includes = []

  # Specification of build inputs like source files, Makefiles, etc
  [Build.Input]

    [Build.Input.Files]
    # Valid variables: $ROOT
    paths = ["hello.py"]


  # Specification of build outputs produced by the [Build.command]
  [Build.Output]
    
    tag = "$GITCOMMIT"

    [[Build.Output.File]]

    # Path relative to the application directory, valid variables: $APPNAME
    path = "output/python.txt"

     # Copy the file to a local directory
    [Build.Output.File.FileCopy]

    # Destination directory
    path = "/tmp/baur_build_artifacts/$APPNAME-$GITCOMMIT"


